//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VehicleDbEntities : DbContext
    {
        public VehicleDbEntities()
            : base("name=VehicleDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vrs_drive> vrs_drive { get; set; }
        public DbSet<vrs_driver> vrs_driver { get; set; }
        public DbSet<vrs_expense> vrs_expense { get; set; }
        public DbSet<vrs_fuel> vrs_fuel { get; set; }
        public DbSet<vrs_insurance> vrs_insurance { get; set; }
        public DbSet<vrs_license> vrs_license { get; set; }
        public DbSet<vrs_maintenance> vrs_maintenance { get; set; }
        public DbSet<vrs_maintenance_task> vrs_maintenance_task { get; set; }
        public DbSet<vrs_place> vrs_place { get; set; }
        public DbSet<vrs_repair> vrs_repair { get; set; }
        public DbSet<vrs_repair_spare_part> vrs_repair_spare_part { get; set; }
        public DbSet<vrs_spare_part> vrs_spare_part { get; set; }
        public DbSet<vrs_supplier> vrs_supplier { get; set; }
        public DbSet<vrs_supplier_spare_part> vrs_supplier_spare_part { get; set; }
        public DbSet<vrs_supplier_tire> vrs_supplier_tire { get; set; }
        public DbSet<vrs_task> vrs_task { get; set; }
        public DbSet<vrs_task_spare_part> vrs_task_spare_part { get; set; }
        public DbSet<vrs_tire> vrs_tire { get; set; }
        public DbSet<vrs_vehicle> vrs_vehicle { get; set; }
        public DbSet<vrs_vehicle_image> vrs_vehicle_image { get; set; }
        public DbSet<vrs_vehicle_tire> vrs_vehicle_tire { get; set; }
    }
}
