//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventory_dbEntities : DbContext
    {
        public inventory_dbEntities()
            : base("name=inventory_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batch> Batch { get; set; }
        public virtual DbSet<BatchVsItems> BatchVsItems { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<ItemCategory> ItemCategory { get; set; }
        public virtual DbSet<ItemImage> ItemImage { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<ReturnedDetails> ReturnedDetails { get; set; }
        public virtual DbSet<SellingItem> SellingItem { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<SupplierPayment> SupplierPayment { get; set; }
        public virtual DbSet<WarrantyDetails> WarrantyDetails { get; set; }
    }
}
