//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_image
    {
        public string ID { get; set; }
        public string RETURNED_DETAILS_ID { get; set; }
        public string BATCH_VS_ITEMS_ID { get; set; }
        public string ITEMFILE_NAME { get; set; }
        public string FILE_TYPE { get; set; }
        public Nullable<int> FILE_SIZE { get; set; }
        public byte[] FILE_CONTENT { get; set; }
        public Nullable<bool> SAVE { get; set; }
        public string INSERT_USER { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE_TIME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_TIME { get; set; }
        public string REMARK { get; set; }
        public Nullable<sbyte> STATUS { get; set; }
    
        public virtual batch_vs_items batch_vs_items { get; set; }
        public virtual returned_details returned_details { get; set; }
    }
}
