//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnedDetails
    {
        public ReturnedDetails()
        {
            this.ItemImage = new HashSet<ItemImage>();
        }
    
        public string Id { get; set; }
        public string ItemId { get; set; }
        public string ReturnNo { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public Nullable<sbyte> Status { get; set; }
        public string Description { get; set; }
        public string InsertUser { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<ItemImage> ItemImage { get; set; }
        public virtual SellingItem SellingItem { get; set; }
    }
}
