//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staff()
        {
            this.invoices = new HashSet<invoice>();
        }
    
        public string ID { get; set; }
        public string EMPLOYEE_NO { get; set; }
        public string STAFF_FNAME { get; set; }
        public string STAFF_MNAME { get; set; }
        public string STAFF_LNAME { get; set; }
        public string PASSWORD { get; set; }
        public string ROLE { get; set; }
        public string TELEPHONE { get; set; }
        public string TELEPHONE2 { get; set; }
        public string EMAIL { get; set; }
        public string INSERT_USER { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE_TIME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_TIME { get; set; }
        public string REMARKS { get; set; }
        public Nullable<sbyte> STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice> invoices { get; set; }
    }
}
