//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_payment
    {
        public string ID { get; set; }
        public string BATCH_ID { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<System.DateTime> SUP_PAYMNT_DATE { get; set; }
        public string METHOD { get; set; }
        public string INSERT_USER { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE_TIME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_TIME { get; set; }
        public string REMARK { get; set; }
        public string FK_PART_BATCH_ID { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> CHEQUE_DATE { get; set; }
    
        public virtual batch batch { get; set; }
    }
}
