//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleTire
    {
        public string TireId { get; set; }
        public string VehicleId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Reason { get; set; }
        public string Wheel { get; set; }
        public Nullable<int> Milage { get; set; }
        public Nullable<sbyte> Status { get; set; }
        public string InsertUser { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    
        public virtual Tire Tire { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
