//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrs_spare_part
    {
        public vrs_spare_part()
        {
            this.vrs_supplier_has_vrs_spare_part = new HashSet<vrs_supplier_has_vrs_spare_part>();
            this.vrs_repair = new HashSet<vrs_repair>();
            this.vrs_service_task = new HashSet<vrs_service_task>();
        }
    
        public string ID { get; set; }
        public string PART_NUMBER { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string PART_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<sbyte> STATUS { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE_TIME { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_TIME { get; set; }
    
        public virtual ICollection<vrs_supplier_has_vrs_spare_part> vrs_supplier_has_vrs_spare_part { get; set; }
        public virtual ICollection<vrs_repair> vrs_repair { get; set; }
        public virtual ICollection<vrs_service_task> vrs_service_task { get; set; }
    }
}
