//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrs_supplier
    {
        public vrs_supplier()
        {
            this.vrs_supplier_has_vrs_spare_part = new HashSet<vrs_supplier_has_vrs_spare_part>();
            this.vrs_supplier_has_vrs_tire = new HashSet<vrs_supplier_has_vrs_tire>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string TELEPHONE1 { get; set; }
        public string TELEPHONE2 { get; set; }
        public Nullable<System.DateTime> INSERT_DATETIME { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<sbyte> STATUS { get; set; }
        public string REMARK { get; set; }
    
        public virtual ICollection<vrs_supplier_has_vrs_spare_part> vrs_supplier_has_vrs_spare_part { get; set; }
        public virtual ICollection<vrs_supplier_has_vrs_tire> vrs_supplier_has_vrs_tire { get; set; }
    }
}
