//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrs_supplier_has_vrs_tire
    {
        public string vrs_supplier_ID { get; set; }
        public string vrs_tire_ID { get; set; }
        public byte[] INVOICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual vrs_supplier vrs_supplier { get; set; }
        public virtual vrs_tire vrs_tire { get; set; }
    }
}
