//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrs_driver
    {
        public vrs_driver()
        {
            this.vrs_drive = new HashSet<vrs_drive>();
        }
    
        public string ID { get; set; }
        public string FULL_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string TELEPHONE { get; set; }
        public string MOBILE1 { get; set; }
        public string MOBILE2 { get; set; }
        public byte[] IMAGE { get; set; }
        public string LICENSE_TYPE { get; set; }
        public string LICENSE_NUMBER { get; set; }
        public byte[] LICENSE_IMAGE { get; set; }
        public Nullable<System.DateTime> LICENSE_ISSUED_DATE { get; set; }
        public Nullable<System.DateTime> LICENSE_EXPIRY_DATE { get; set; }
        public string JOB_TYPE { get; set; }
        public Nullable<sbyte> STATUS { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE_TIME { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_TIME { get; set; }
        public string REMARK { get; set; }
    
        public virtual ICollection<vrs_drive> vrs_drive { get; set; }
    }
}
