//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrs_tire
    {
        public vrs_tire()
        {
            this.vrs_supplier_has_vrs_tire = new HashSet<vrs_supplier_has_vrs_tire>();
            this.vrs_tire_has_vrs_vehicle = new HashSet<vrs_tire_has_vrs_vehicle>();
        }
    
        public string ID { get; set; }
        public string BRAND { get; set; }
        public Nullable<sbyte> RIM_SIZE { get; set; }
        public string SIZE_CODE { get; set; }
        public string MANUFACTURE_DATE_CODE { get; set; }
        public string TYPE { get; set; }
        public string CONDITION { get; set; }
        public Nullable<System.DateTime> INSERT_DATETIME { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<sbyte> STATUS { get; set; }
        public string REMARK { get; set; }
    
        public virtual ICollection<vrs_supplier_has_vrs_tire> vrs_supplier_has_vrs_tire { get; set; }
        public virtual ICollection<vrs_tire_has_vrs_vehicle> vrs_tire_has_vrs_vehicle { get; set; }
    }
}
