//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrs_license
    {
        public string ID { get; set; }
        public string LICENSE_NUMBER { get; set; }
        public string VALIDITY_PERIOD { get; set; }
        public string CLASS { get; set; }
        public string OWNER_NAME { get; set; }
        public Nullable<float> UNLADEN_WEIGHT { get; set; }
        public Nullable<int> SEATS { get; set; }
        public Nullable<float> ANNUAL_FEE { get; set; }
        public Nullable<float> ARREARS { get; set; }
        public Nullable<float> ENV_CONTROL_LEVY { get; set; }
        public Nullable<float> TOTAL { get; set; }
        public Nullable<System.DateTime> VALID_FROM { get; set; }
        public Nullable<System.DateTime> VALID_TO { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public string PROVINCE { get; set; }
        public string EMISSION_TEST_NUMBER { get; set; }
        public byte[] EMISSION_TEST_IMAGE { get; set; }
        public byte[] LICENSE_IMAGE { get; set; }
        public Nullable<sbyte> STATUS { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE_TIME { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_TIME { get; set; }
        public string vrs_vehicle_ID { get; set; }
    
        public virtual vrs_vehicle vrs_vehicle { get; set; }
    }
}
