//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrs_drive
    {
        public vrs_drive()
        {
            this.vrs_place = new HashSet<vrs_place>();
        }
    
        public string ID { get; set; }
        public Nullable<System.DateTime> START_DATE_TIME { get; set; }
        public Nullable<float> START_ODOMETER { get; set; }
        public Nullable<System.DateTime> END_DATE_TIME { get; set; }
        public Nullable<float> END_ODOMETER { get; set; }
        public string FROM { get; set; }
        public string TO { get; set; }
        public string IS_SHEDULED { get; set; }
        public Nullable<sbyte> STATUS { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE_TIME { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_TIME { get; set; }
        public string vrs_vehicle_ID { get; set; }
        public string vrs_driver_ID { get; set; }
    
        public virtual vrs_driver vrs_driver { get; set; }
        public virtual vrs_vehicle vrs_vehicle { get; set; }
        public virtual ICollection<vrs_place> vrs_place { get; set; }
    }
}
