//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrs_tire_has_vrs_vehicle
    {
        public string vrs_tire_ID { get; set; }
        public string vrs_vehicle_ID { get; set; }
        public Nullable<System.DateTime> DATE_TIME { get; set; }
        public string REASON { get; set; }
        public string WHEEL { get; set; }
        public Nullable<int> MILAGE { get; set; }
    
        public virtual vrs_tire vrs_tire { get; set; }
        public virtual vrs_vehicle vrs_vehicle { get; set; }
    }
}
