-- MySQL Script generated by MySQL Workbench
-- 08/07/15 08:30:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vehicledb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vehicledb` ;

-- -----------------------------------------------------
-- Schema vehicledb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vehicledb` DEFAULT CHARACTER SET utf8 ;
USE `vehicledb` ;

-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_vehicle` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_vehicle` (
  `ID` VARCHAR(32) NOT NULL,
  `REGISTRATION_NUMBER` VARCHAR(16) NULL DEFAULT NULL,
  `CATEGORY` VARCHAR(32) NULL DEFAULT NULL,
  `TYPE` VARCHAR(32) NULL DEFAULT NULL,
  `MAKE` VARCHAR(32) NULL DEFAULT NULL,
  `MODEL` VARCHAR(32) NULL DEFAULT NULL,
  `FUEL_TYPE` SET('PETROL','DIESEL','ELECTRIC','HYBRID','OTHER') NULL DEFAULT NULL,
  `ENGINE_NUMBER` VARCHAR(32) NULL DEFAULT NULL,
  `CHASSIS_NUMBER` VARCHAR(32) NULL DEFAULT NULL,
  `YEAR_MANUFACTURE` VARCHAR(8) NULL DEFAULT NULL,
  `DATE_IMPORT` VARCHAR(8) NULL DEFAULT NULL,
  `DATE_REGISTER` VARCHAR(8) NULL DEFAULT NULL,
  `REGISTRATION_CERTIFICATE` BLOB NULL DEFAULT NULL,
  `NUM_WHEELS` TINYINT NULL DEFAULT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `REGISTRATION_NUMBER_UNIQUE` (`REGISTRATION_NUMBER` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_driver` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_driver` (
  `ID` VARCHAR(32) NOT NULL DEFAULT '',
  `FULL_NAME` VARCHAR(255) NULL DEFAULT NULL,
  `FIRST_NAME` VARCHAR(32) NULL DEFAULT NULL,
  `LAST_NAME` VARCHAR(32) NULL DEFAULT NULL,
  `ADDRESS` VARCHAR(255) NULL DEFAULT NULL,
  `TELEPHONE` VARCHAR(15) NULL DEFAULT NULL,
  `MOBILE1` VARCHAR(15) NULL DEFAULT NULL,
  `MOBILE2` VARCHAR(15) NULL DEFAULT NULL,
  `IMAGE` BLOB NULL DEFAULT NULL,
  `LICENSE_TYPE` VARCHAR(15) NULL DEFAULT NULL,
  `LICENSE_NUMBER` VARCHAR(32) NULL DEFAULT NULL,
  `LICENSE_IMAGE` BLOB NULL DEFAULT NULL,
  `LICENSE_ISSUED_DATE` DATE NULL,
  `LICENSE_EXPIRY_DATE` DATE NULL,
  `JOB_TYPE` SET('Temporary', 'Permonent', 'Contract') NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `REMARK` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_drive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_drive` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_drive` (
  `ID` VARCHAR(32) NOT NULL DEFAULT '',
  `START_DATE_TIME` DATE NULL DEFAULT NULL,
  `START_ODOMETER` FLOAT(7,1) NULL DEFAULT NULL,
  `END_DATE_TIME` DATE NULL DEFAULT NULL,
  `END_ODOMETER` FLOAT(7,1) NULL DEFAULT NULL,
  `FROM` VARCHAR(15) NULL DEFAULT NULL,
  `TO` VARCHAR(15) NULL DEFAULT NULL,
  `IS_SHEDULED` ENUM('YES','NO') NULL DEFAULT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `vrs_vehicle_ID` VARCHAR(32) NOT NULL,
  `vrs_driver_ID` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_vrs_drive_vrs_vehicle1_idx` (`vrs_vehicle_ID` ASC),
  INDEX `fk_vrs_drive_vrs_driver1_idx` (`vrs_driver_ID` ASC),
  CONSTRAINT `fk_vrs_drive_vrs_vehicle1`
    FOREIGN KEY (`vrs_vehicle_ID`)
    REFERENCES `vehicledb`.`vrs_vehicle` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vrs_drive_vrs_driver1`
    FOREIGN KEY (`vrs_driver_ID`)
    REFERENCES `vehicledb`.`vrs_driver` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_expense`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_expense` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_expense` (
  `ID` VARCHAR(32) NOT NULL DEFAULT '',
  `AMOUNT` FLOAT(7,1) NULL DEFAULT NULL,
  `DATE_TIME` DATE NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `vrs_vehicle_ID` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_vrs_expense_vrs_vehicle1_idx` (`vrs_vehicle_ID` ASC),
  CONSTRAINT `fk_vrs_expense_vrs_vehicle1`
    FOREIGN KEY (`vrs_vehicle_ID`)
    REFERENCES `vehicledb`.`vrs_vehicle` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_fuel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_fuel` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_fuel` (
  `ID` VARCHAR(32) NOT NULL DEFAULT '',
  `AMOUNT` FLOAT(7,1) NULL DEFAULT NULL,
  `VOLUME` FLOAT(5,1) NULL DEFAULT NULL,
  `ODOMETER` FLOAT(7,1) NULL DEFAULT NULL,
  `DATE_TIME` DATE NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `vrs_vehicle_ID` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_vrs_fuel_vrs_vehicle1_idx` (`vrs_vehicle_ID` ASC),
  CONSTRAINT `fk_vrs_fuel_vrs_vehicle1`
    FOREIGN KEY (`vrs_vehicle_ID`)
    REFERENCES `vehicledb`.`vrs_vehicle` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_insurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_insurance` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_insurance` (
  `ID` VARCHAR(32) NOT NULL,
  `POLICY_NUMBER` VARCHAR(32) NULL DEFAULT NULL,
  `COMPANY` VARCHAR(32) NULL DEFAULT NULL,
  `OWNER_NAME` VARCHAR(32) NULL DEFAULT NULL,
  `OWNER_ADDRESS` VARCHAR(32) NULL DEFAULT NULL,
  `FROM_DATE` DATETIME NULL DEFAULT NULL,
  `TO_DATE` DATETIME NULL DEFAULT NULL,
  `ISSUE_DATE` DATETIME NULL DEFAULT NULL,
  `IMAGE` BLOB NULL DEFAULT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `vrs_vehicle_ID` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `POLICY_NUMBER_UNIQUE` (`POLICY_NUMBER` ASC),
  INDEX `fk_vrs_insurance_vrs_vehicle_idx` (`vrs_vehicle_ID` ASC),
  CONSTRAINT `fk_vrs_insurance_vrs_vehicle`
    FOREIGN KEY (`vrs_vehicle_ID`)
    REFERENCES `vehicledb`.`vrs_vehicle` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_license`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_license` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_license` (
  `ID` VARCHAR(32) NOT NULL DEFAULT '',
  `LICENSE_NUMBER` VARCHAR(64) NULL DEFAULT NULL,
  `VALIDITY_PERIOD` VARCHAR(64) NULL DEFAULT NULL,
  `CLASS` VARCHAR(64) NULL DEFAULT NULL,
  `OWNER_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `UNLADEN_WEIGHT` FLOAT(8,1) NULL DEFAULT NULL,
  `SEATS` INT(11) NULL DEFAULT NULL,
  `ANNUAL_FEE` FLOAT(6,1) NULL DEFAULT NULL,
  `ARREARS` FLOAT(6,1) NULL DEFAULT NULL,
  `ENV_CONTROL_LEVY` FLOAT(6,1) NULL DEFAULT NULL,
  `TOTAL` FLOAT(6,1) NULL DEFAULT NULL,
  `VALID_FROM` DATE NULL DEFAULT NULL,
  `VALID_TO` DATE NULL DEFAULT NULL,
  `ISSUE_DATE` DATE NULL DEFAULT NULL,
  `PROVINCE` VARCHAR(64) NULL DEFAULT NULL,
  `EMISSION_TEST_NUMBER` VARCHAR(64) NULL DEFAULT NULL,
  `EMISSION_TEST_IMAGE` BLOB NULL DEFAULT NULL,
  `LICENSE_IMAGE` BLOB NULL DEFAULT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `vrs_vehicle_ID` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_vrs_license_vrs_vehicle1_idx` (`vrs_vehicle_ID` ASC),
  CONSTRAINT `fk_vrs_license_vrs_vehicle1`
    FOREIGN KEY (`vrs_vehicle_ID`)
    REFERENCES `vehicledb`.`vrs_vehicle` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_place` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_place` (
  `ID` VARCHAR(32) NOT NULL DEFAULT '',
  `ARRIVAL_DATE_TIME` DATE NULL DEFAULT NULL,
  `ODOMETER` FLOAT(7,1) NULL DEFAULT NULL,
  `DEPARTURE_DATE_TIME` DATE NULL DEFAULT NULL,
  `JOB_DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `vrs_drive_ID` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_vrs_place_vrs_drive1_idx` (`vrs_drive_ID` ASC),
  CONSTRAINT `fk_vrs_place_vrs_drive1`
    FOREIGN KEY (`vrs_drive_ID`)
    REFERENCES `vehicledb`.`vrs_drive` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_repair`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_repair` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_repair` (
  `ID` VARCHAR(32) NOT NULL DEFAULT '',
  `DATE_TIME` DATE NULL DEFAULT NULL,
  `GARAGE_NAME` VARCHAR(100) NULL DEFAULT NULL,
  `REPAIR TYPE` VARCHAR(255) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `INVOICE_IMAGE` BLOB NULL DEFAULT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `vrs_vehicle_ID` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_vrs_repair_vrs_vehicle1_idx` (`vrs_vehicle_ID` ASC),
  CONSTRAINT `fk_vrs_repair_vrs_vehicle1`
    FOREIGN KEY (`vrs_vehicle_ID`)
    REFERENCES `vehicledb`.`vrs_vehicle` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_maintenance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_maintenance` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_maintenance` (
  `ID` VARCHAR(32) NOT NULL,
  `METER_READING` VARCHAR(8) NULL DEFAULT NULL,
  `DATE` DATE NULL DEFAULT NULL,
  `NEXT_METER_READING` VARCHAR(8) NULL DEFAULT NULL,
  `NEXT_DATE` DATE NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `INVOICE_IMAGE` BLOB NULL DEFAULT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `vrs_vehicle_ID` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_vrs_service_vrs_vehicle1_idx` (`vrs_vehicle_ID` ASC),
  CONSTRAINT `fk_vrs_service_vrs_vehicle1`
    FOREIGN KEY (`vrs_vehicle_ID`)
    REFERENCES `vehicledb`.`vrs_vehicle` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_task` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_task` (
  `ID` VARCHAR(32) NOT NULL DEFAULT '',
  `NAME` VARCHAR(64) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_spare_part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_spare_part` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_spare_part` (
  `ID` VARCHAR(32) NOT NULL DEFAULT '',
  `PART_NUMBER` VARCHAR(64) NULL DEFAULT NULL,
  `SERIAL_NUMBER` VARCHAR(64) NULL DEFAULT NULL,
  `PART_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `PRICE` FLOAT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `UNIT` VARCHAR(45) NULL,
  `STOCK` FLOAT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_repair_spare_part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_repair_spare_part` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_repair_spare_part` (
  `vrs_repair_ID` VARCHAR(32) NOT NULL,
  `vrs_spare_part_ID` VARCHAR(32) NOT NULL,
  `PRICE` FLOAT NULL,
  `QUANTITY` FLOAT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`vrs_repair_ID`, `vrs_spare_part_ID`),
  INDEX `fk_vrs_repair_has_vrs_spare_part_vrs_spare_part1_idx` (`vrs_spare_part_ID` ASC),
  INDEX `fk_vrs_repair_has_vrs_spare_part_vrs_repair1_idx` (`vrs_repair_ID` ASC),
  CONSTRAINT `fk_vrs_repair_has_vrs_spare_part_vrs_repair1`
    FOREIGN KEY (`vrs_repair_ID`)
    REFERENCES `vehicledb`.`vrs_repair` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vrs_repair_has_vrs_spare_part_vrs_spare_part1`
    FOREIGN KEY (`vrs_spare_part_ID`)
    REFERENCES `vehicledb`.`vrs_spare_part` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_tire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_tire` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_tire` (
  `ID` CHAR(32) NOT NULL,
  `BRAND` VARCHAR(255) NULL,
  `RIM_SIZE` TINYINT NULL,
  `SIZE_CODE` VARCHAR(32) NULL,
  `MANUFACTURE_DATE_CODE` CHAR(4) NULL,
  `TYPE` ENUM('Tube-less', 'Tube') NULL,
  `CONDITION` SET('Brand new', 'Used', 'Rebuilt') NULL,
  `INSERT_DATETIME` DATE NULL,
  `INSERT_USER` CHAR(32) NULL,
  `UPDATE_DATETIME` DATE NULL,
  `UPDATE_USER` CHAR(32) NULL,
  `STATUS` TINYINT NULL,
  `REMARK` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_supplier` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_supplier` (
  `ID` CHAR(32) NOT NULL,
  `NAME` VARCHAR(255) NULL,
  `ADDRESS` VARCHAR(255) NULL,
  `TELEPHONE1` VARCHAR(15) NULL,
  `TELEPHONE2` VARCHAR(15) NULL,
  `INSERT_DATETIME` DATE NULL,
  `INSERT_USER` CHAR(32) NULL,
  `UPDATE_DATETIME` DATE NULL,
  `UPDATE_USER` CHAR(32) NULL,
  `STATUS` TINYINT NULL,
  `REMARK` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_vehicle_tire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_vehicle_tire` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_vehicle_tire` (
  `vrs_tire_ID` CHAR(32) NOT NULL,
  `vrs_vehicle_ID` VARCHAR(32) NOT NULL,
  `DATE_TIME` DATETIME NULL,
  `REASON` VARCHAR(255) NULL,
  `WHEEL` VARCHAR(100) NULL,
  `MILAGE` INT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`vrs_tire_ID`, `vrs_vehicle_ID`),
  INDEX `fk_vrs_tire_has_vrs_vehicle_vrs_vehicle1_idx` (`vrs_vehicle_ID` ASC),
  INDEX `fk_vrs_tire_has_vrs_vehicle_vrs_tire1_idx` (`vrs_tire_ID` ASC),
  CONSTRAINT `fk_vrs_tire_has_vrs_vehicle_vrs_tire1`
    FOREIGN KEY (`vrs_tire_ID`)
    REFERENCES `vehicledb`.`vrs_tire` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vrs_tire_has_vrs_vehicle_vrs_vehicle1`
    FOREIGN KEY (`vrs_vehicle_ID`)
    REFERENCES `vehicledb`.`vrs_vehicle` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_supplier_tire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_supplier_tire` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_supplier_tire` (
  `vrs_supplier_ID` CHAR(32) NOT NULL,
  `vrs_tire_ID` CHAR(32) NOT NULL,
  `INVOICE` BLOB NULL,
  `QUANTITY` INT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`vrs_supplier_ID`, `vrs_tire_ID`),
  INDEX `fk_vrs_supplier_has_vrs_tire_vrs_tire1_idx` (`vrs_tire_ID` ASC),
  INDEX `fk_vrs_supplier_has_vrs_tire_vrs_supplier1_idx` (`vrs_supplier_ID` ASC),
  CONSTRAINT `fk_vrs_supplier_has_vrs_tire_vrs_supplier1`
    FOREIGN KEY (`vrs_supplier_ID`)
    REFERENCES `vehicledb`.`vrs_supplier` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vrs_supplier_has_vrs_tire_vrs_tire1`
    FOREIGN KEY (`vrs_tire_ID`)
    REFERENCES `vehicledb`.`vrs_tire` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_supplier_spare_part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_supplier_spare_part` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_supplier_spare_part` (
  `vrs_supplier_ID` CHAR(32) NOT NULL,
  `vrs_spare_part_ID` VARCHAR(32) NOT NULL,
  `QUANTITY` INT NULL,
  `INVOICE` BLOB NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`vrs_supplier_ID`, `vrs_spare_part_ID`),
  INDEX `fk_vrs_supplier_has_vrs_spare_part_vrs_spare_part1_idx` (`vrs_spare_part_ID` ASC),
  INDEX `fk_vrs_supplier_has_vrs_spare_part_vrs_supplier1_idx` (`vrs_supplier_ID` ASC),
  CONSTRAINT `fk_vrs_supplier_has_vrs_spare_part_vrs_supplier1`
    FOREIGN KEY (`vrs_supplier_ID`)
    REFERENCES `vehicledb`.`vrs_supplier` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vrs_supplier_has_vrs_spare_part_vrs_spare_part1`
    FOREIGN KEY (`vrs_spare_part_ID`)
    REFERENCES `vehicledb`.`vrs_spare_part` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_vehicle_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_vehicle_image` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_vehicle_image` (
  `ID` VARCHAR(32) NOT NULL,
  `IMAGE` BLOB NULL,
  `SIDE` VARCHAR(100) NULL,
  `INSERT_DATETIME` DATE NULL,
  `INSERT_USER` VARCHAR(32) NULL,
  `UPDATE_DATETIME` DATE NULL,
  `UPDATE_USER` VARCHAR(32) NULL,
  `STATUS` TINYINT NULL,
  `REMARK` VARCHAR(255) NULL,
  `vrs_vehicle_ID` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_vrs_vehicle_image_vrs_vehicle1_idx` (`vrs_vehicle_ID` ASC),
  CONSTRAINT `fk_vrs_vehicle_image_vrs_vehicle1`
    FOREIGN KEY (`vrs_vehicle_ID`)
    REFERENCES `vehicledb`.`vrs_vehicle` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_task_spare_part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_task_spare_part` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_task_spare_part` (
  `vrs_task_ID` VARCHAR(32) NOT NULL,
  `vrs_spare_part_ID` VARCHAR(32) NOT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`vrs_task_ID`, `vrs_spare_part_ID`),
  INDEX `fk_vrs_task_has_vrs_spare_part_vrs_spare_part1_idx` (`vrs_spare_part_ID` ASC),
  INDEX `fk_vrs_task_has_vrs_spare_part_vrs_task1_idx` (`vrs_task_ID` ASC),
  CONSTRAINT `fk_vrs_task_has_vrs_spare_part_vrs_task1`
    FOREIGN KEY (`vrs_task_ID`)
    REFERENCES `vehicledb`.`vrs_task` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vrs_task_has_vrs_spare_part_vrs_spare_part1`
    FOREIGN KEY (`vrs_spare_part_ID`)
    REFERENCES `vehicledb`.`vrs_spare_part` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vehicledb`.`vrs_maintenance_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicledb`.`vrs_maintenance_task` ;

CREATE TABLE IF NOT EXISTS `vehicledb`.`vrs_maintenance_task` (
  `vrs_maintenance_ID` VARCHAR(32) NOT NULL,
  `vrs_task_ID` VARCHAR(32) NOT NULL,
  `STATUS` TINYINT(4) NULL DEFAULT NULL,
  `INSERT_USER` VARCHAR(32) NULL DEFAULT NULL,
  `INSERT_DATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_USER` VARCHAR(32) NULL DEFAULT NULL,
  `UPDATE_DATE_TIME` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`vrs_maintenance_ID`, `vrs_task_ID`),
  INDEX `fk_vrs_maintenance_has_vrs_task_vrs_task1_idx` (`vrs_task_ID` ASC),
  INDEX `fk_vrs_maintenance_has_vrs_task_vrs_maintenance1_idx` (`vrs_maintenance_ID` ASC),
  CONSTRAINT `fk_vrs_maintenance_has_vrs_task_vrs_maintenance1`
    FOREIGN KEY (`vrs_maintenance_ID`)
    REFERENCES `vehicledb`.`vrs_maintenance` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vrs_maintenance_has_vrs_task_vrs_task1`
    FOREIGN KEY (`vrs_task_ID`)
    REFERENCES `vehicledb`.`vrs_task` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
