//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware.Fleet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drive
    {
    	public Drive()
        {
    		this.Place = new HashSet<Place>();
        }
    
        public string Id { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<float> StartOdometer { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<float> EndOdometer { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string IsSheduled { get; set; }
        public Nullable<sbyte> Status { get; set; }
        public string InsertUser { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string VehicleId { get; set; }
        public string DriverId { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual ICollection<Place> Place { get; set; }
    }
}
