//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Fleet.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VehicleDbEntities : DbContext
    {
        public VehicleDbEntities()
            : base("name=VehicleDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Drive> Drive { get; set; }
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<Expense> Expense { get; set; }
        public virtual DbSet<Fuel> Fuel { get; set; }
        public virtual DbSet<Insurance> Insurance { get; set; }
        public virtual DbSet<License> License { get; set; }
        public virtual DbSet<Maintenance> Maintenance { get; set; }
        public virtual DbSet<MaintenanceTask> MaintenanceTask { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Repair> Repair { get; set; }
        public virtual DbSet<RepairSparePart> RepairSparePart { get; set; }
        public virtual DbSet<SparePart> SparePart { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<SupplierSparePart> SupplierSparePart { get; set; }
        public virtual DbSet<SupplierTire> SupplierTire { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<TaskSparePart> TaskSparePart { get; set; }
        public virtual DbSet<Tire> Tire { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
        public virtual DbSet<VehicleImage> VehicleImage { get; set; }
        public virtual DbSet<VehicleTire> VehicleTire { get; set; }
    }
}
