//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware.Fleet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePart
    {
    	public SparePart()
        {
    		this.RepairSparePart = new HashSet<RepairSparePart>();
    		this.SupplierSparePart = new HashSet<SupplierSparePart>();
    		this.TaskSparePart = new HashSet<TaskSparePart>();
        }
    
        public string Id { get; set; }
        public string PartNumber { get; set; }
        public string SerialNumber { get; set; }
        public string PartName { get; set; }
        public Nullable<float> Price { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public Nullable<float> Stock { get; set; }
        public Nullable<sbyte> Status { get; set; }
        public string InsertUser { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    
        public virtual ICollection<RepairSparePart> RepairSparePart { get; set; }
        public virtual ICollection<SupplierSparePart> SupplierSparePart { get; set; }
        public virtual ICollection<TaskSparePart> TaskSparePart { get; set; }
    }
}
