//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoerITSoftware.Fleet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
    	public Supplier()
        {
    		this.SupplierSparePart = new HashSet<SupplierSparePart>();
    		this.SupplierTire = new HashSet<SupplierTire>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public Nullable<System.DateTime> InsertDatetime { get; set; }
        public string InsertUser { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<sbyte> Status { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<SupplierSparePart> SupplierSparePart { get; set; }
        public virtual ICollection<SupplierTire> SupplierTire { get; set; }
    }
}
