//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch_vs_items_has_order
    {
        public string batch_vs_items_ID { get; set; }
        public string order_ID { get; set; }
        public sbyte IS_DELETED { get; set; }
    
        public virtual batch_vs_items batch_vs_items { get; set; }
        public virtual order order { get; set; }
    }
}
