//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Inventory.Model
{
    using DoerITSoftware.Core.Inventory.Interfaces;
    using System;
    using System.Collections.Generic;

    public partial class BatchVsItemsHasOrder : IBatchVsItemsHasOrder
    {
        public string BatchVsItemsId { get; set; }
        public string OrderId { get; set; }
        public string InsertUser { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public Nullable<sbyte> Status { get; set; }
        public sbyte IsDeleted { get; set; }
        public string Id { get; set; }
    
        public virtual BatchVsItems BatchVsItems { get; set; }
        public virtual Order Order { get; set; }
    }
}
