//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch_vs_items
    {
        public batch_vs_items()
        {
            this.batch_vs_items1 = new HashSet<batch_vs_items>();
            this.batch_vs_items_has_order = new HashSet<batch_vs_items_has_order>();
            this.selling_item = new HashSet<selling_item>();
            this.item_image = new HashSet<item_image>();
        }
    
        public string ID { get; set; }
        public string BATCH_ID { get; set; }
        public string ITEM_CATEGORY_ID { get; set; }
        public string ITEM_SUB_CATEGORY_ID { get; set; }
        public string MANUFACTURER { get; set; }
        public string COUNTRY { get; set; }
        public string MODEL { get; set; }
        public Nullable<int> QTY { get; set; }
        public string UNIT { get; set; }
        public Nullable<double> UNIT_COST { get; set; }
        public Nullable<double> UNIT_PRICE { get; set; }
        public string TYPE { get; set; }
        public string DEFECTS { get; set; }
        public string DESCRIPTION { get; set; }
        public string WARRANTY_PERIOD { get; set; }
        public string INSERT_USER { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE_TIME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_TIME { get; set; }
        public string REMARK { get; set; }
        public Nullable<sbyte> STATUS { get; set; }
        public sbyte IS_DELETED { get; set; }
        public string batch_vs_items_ID { get; set; }
    
        public virtual batch batch { get; set; }
        public virtual ICollection<batch_vs_items> batch_vs_items1 { get; set; }
        public virtual batch_vs_items batch_vs_items2 { get; set; }
        public virtual ICollection<batch_vs_items_has_order> batch_vs_items_has_order { get; set; }
        public virtual item_category item_category { get; set; }
        public virtual item_sub_category item_sub_category { get; set; }
        public virtual ICollection<selling_item> selling_item { get; set; }
        public virtual ICollection<item_image> item_image { get; set; }
    }
}
