//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Inventory.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventory_dbEntities : DbContext
    {
        public inventory_dbEntities()
            : base("name=inventory_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<batch> batches { get; set; }
        public DbSet<batch_vs_items> batch_vs_items { get; set; }
        public DbSet<batch_vs_items_has_order> batch_vs_items_has_order { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<i_staff> i_staff { get; set; }
        public DbSet<invoice> invoices { get; set; }
        public DbSet<item_category> item_category { get; set; }
        public DbSet<item_image> item_image { get; set; }
        public DbSet<item_sub_category> item_sub_category { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<payment> payments { get; set; }
        public DbSet<returned_details> returned_details { get; set; }
        public DbSet<selling_item> selling_item { get; set; }
        public DbSet<supplier> suppliers { get; set; }
        public DbSet<supplier_has_item_category> supplier_has_item_category { get; set; }
        public DbSet<supplier_payment> supplier_payment { get; set; }
        public DbSet<warranty_details> warranty_details { get; set; }
    }
}
