//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Inventory.Model
{
    using DoerITSoftware.Core.Inventory.Interfaces;
    using System;
    using System.Collections.Generic;

    public partial class Invoice : IInvoice
    {
        public Invoice()
        {
            this.Payments = new HashSet<Payment>();
            this.SellingItem = new HashSet<SellingItem>();
        }
    
        public string Id { get; set; }
        public string StaffId { get; set; }
        public string CustomerId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> NetTotal { get; set; }
        public string Terms { get; set; }
        public string InsertUser { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public Nullable<sbyte> Status { get; set; }
        public sbyte IsDeleted { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual IStaff IStaff { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<SellingItem> SellingItem { get; set; }
    }
}
