//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public invoice()
        {
            this.payments = new HashSet<payment>();
            this.selling_item = new HashSet<selling_item>();
        }
    
        public string ID { get; set; }
        public string STAFF_ID { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<double> SUB_TOTAL { get; set; }
        public Nullable<double> DISCOUNT { get; set; }
        public Nullable<double> NET_TOTAL { get; set; }
        public string TERMS { get; set; }
        public string INSERT_USER { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE_TIME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_TIME { get; set; }
        public string REMARK { get; set; }
        public Nullable<sbyte> STATUS { get; set; }
        public sbyte IS_DELETED { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual i_staff i_staff { get; set; }
        public virtual ICollection<payment> payments { get; set; }
        public virtual ICollection<selling_item> selling_item { get; set; }
    }
}
