//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.batch_vs_items_has_order = new HashSet<batch_vs_items_has_order>();
        }
    
        public string ID { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string ORDER_NO { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<sbyte> ORDER_STATUS { get; set; }
        public string INSERT_USER { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE_TIME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_TIME { get; set; }
        public string REMARK { get; set; }
        public Nullable<sbyte> STATUS { get; set; }
        public sbyte IS_DELETED { get; set; }
    
        public virtual ICollection<batch_vs_items_has_order> batch_vs_items_has_order { get; set; }
        public virtual customer customer { get; set; }
    }
}
