//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class selling_item
    {
        public selling_item()
        {
            this.returned_details = new HashSet<returned_details>();
            this.warranty_details = new HashSet<warranty_details>();
        }
    
        public string ID { get; set; }
        public string BATCH_VS_ITEMS_ID { get; set; }
        public string INVOICE_ID { get; set; }
        public string QR_CODE { get; set; }
        public string SERIAL_NO { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<double> DISCOUNT { get; set; }
        public Nullable<double> SOLD_PRICE { get; set; }
        public Nullable<sbyte> STATUS { get; set; }
        public Nullable<int> RETURN_STATUS { get; set; }
        public string RETURN_COMMENT { get; set; }
        public string INSERT_USER { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE_TIME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_TIME { get; set; }
        public string REMARK { get; set; }
        public sbyte IS_DELETED { get; set; }
    
        public virtual batch_vs_items batch_vs_items { get; set; }
        public virtual invoice invoice { get; set; }
        public virtual ICollection<returned_details> returned_details { get; set; }
        public virtual ICollection<warranty_details> warranty_details { get; set; }
    }
}
