//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Inventory.Model
{
    using DoerITSoftware.Core.Inventory.Interfaces;
    using System;
    using System.Collections.Generic;

    public partial class SellingItem : ISellingItem
    {
        public SellingItem()
        {
            this.ReturnedDetails = new HashSet<ReturnedDetails>();
            this.WarrantyDetails = new HashSet<WarrantyDetails>();
        }
    
        public string Id { get; set; }
        public string BatchVsItemsId { get; set; }
        public string InvoiceId { get; set; }
        public string QrCode { get; set; }
        public string SerialNo { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> SoldPrice { get; set; }
        public Nullable<int> ReturnStatus { get; set; }
        public string ReturnComment { get; set; }
        public string InsertUser { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public Nullable<sbyte> Status { get; set; }
        public sbyte IsDeleted { get; set; }
    
        public virtual BatchVsItems BatchVsItems { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual ICollection<ReturnedDetails> ReturnedDetails { get; set; }
        public virtual ICollection<WarrantyDetails> WarrantyDetails { get; set; }
    }
}
