//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.batches = new HashSet<batch>();
            this.supplier_has_item_category = new HashSet<supplier_has_item_category>();
        }
    
        public string ID { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public string INSERT_USER { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE_TIME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_TIME { get; set; }
        public string REMARK { get; set; }
        public Nullable<sbyte> STATUS { get; set; }
        public sbyte IS_DELETED { get; set; }
    
        public virtual ICollection<batch> batches { get; set; }
        public virtual ICollection<supplier_has_item_category> supplier_has_item_category { get; set; }
    }
}
