//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierPayment
    {
        public string Id { get; set; }
        public string BatchId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> SupPaymntDate { get; set; }
        public string Method { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string Comment { get; set; }
        public string InsertUser { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public Nullable<sbyte> Status { get; set; }
        public sbyte IsDeleted { get; set; }
    
        public virtual Batch Batch { get; set; }
    }
}
