//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_has_item_category
    {
        public string supplier_ID { get; set; }
        public string item_category_ID { get; set; }
        public sbyte IS_DELETED { get; set; }
    
        public virtual item_category item_category { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
